#!/usr/bin/env ruby

var = `heroku config:get MONGOHQ_URL 2> /dev/null`.strip

if !var.empty? and m = var.match(/^mongodb:\/\/(.+):(.+)@(.+)$/)
  command = "mongo -u #{m[1]} -p #{m[2]} #{m[3]}"
  exec command
else
  puts "Error. Run this command from an app folder."
end
